services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloud-file-storage-net
  redis:
    image: redis:8.6.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cloud-file-storage-net
  redis-insight:
    image: redis/redisinsight:3.0
    container_name: redisinsight
    restart: always
    depends_on:
      - redis
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    networks:
      - cloud-file-storage-net
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    restart: always
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio:/data
    networks:
      - cloud-file-storage-net

volumes:
  redis-insight:
  postgres_data:
  minio:

networks:
  cloud-file-storage-net:
    driver: bridge