spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

minio:
  security:
    url: ${MINIO_URL}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
  storage:
    bucketName: user-files
    connect-timeout: 5s
    read-timeout: 30s
    write-timeout: 30s
    call-timeout: 30s
    deletion-batch-size: 50

