spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev-db
    username: dev-user
    password: dev-password
  data:
    redis:
      host: localhost
      port: 6379

minio:
  security:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin123
  storage:
    bucketName: dev-bucket
    connect-timeout: 2s
    read-timeout: 10s
    write-timeout: 10s
    call-timeout: 20s
    deletion-batch-size: 10

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Europe/Moscow
  level:
    com.waynehays.cloudfilestorage: DEBUG
