spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev-db
    username: dev-user
    password: dev-password

minio:
  security:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin123
  storage:
    bucketName: dev-bucket
    connect-timeout: 2s
    read-timeout: 10s
    write-timeout: 10s
    call-timeout: 20s
    deletion-batch-size: 10